#pragma once

#include <memory>

#include "log_message_factory.hpp"

namespace helios::logger {

/**
 * @class logger::Logger
 *
 * @brief Logs a message to the configured log sinks with a name.
 *
 * @details
 * - Provides public functions that return an empty log message to the client.
 * - The log message overloads operator<< to create log messages.
 * - When the log message is finished (deleted), the callback provided by this
 *   class will be called to start logging the message to the available log
 *   sinks.
 * - The available sinks could be determined from the file 'log_config.hpp'
 *   which is generated by CMake.
 *
 * @note
 * - All public functions are synchronous.
 * - All public functions are thread-safe.
 */
class Logger {
public:
  /**
   * @brief Constructor.
   *
   * @param name A name to identify the producer of the log message.
   */
  Logger(std::string name);

  /**
   * @brief Destructor.
   */
  ~Logger();

  /**
   * @brief Delete copy and move semantics.
   */
  Logger(const Logger &) = delete;
  Logger &operator=(const Logger &) = delete;
  Logger(Logger &&) = delete;
  Logger &operator=(Logger &&) = delete;

  LogMessageFactory debug();
  LogMessageFactory info();
  LogMessageFactory warn();
  LogMessageFactory error();

private:
  /**
   * @brief Forward declaration for the implementation class.
   */
  class Impl;

  /**
   * @brief Unique pointer to the implementation class.
   */
  std::unique_ptr<Impl> impl_;
}; // class Logger

} // namespace helios::logger
