#pragma once

#include "core/event_loop.hpp"
#include "core/event_queue.hpp"
#include "core/signal_bus.hpp"
#include "file_sink.hpp"
#include "log_macros.hpp"
#include "log_message_factory.hpp"
#include "standard_output_sink.hpp"

namespace helios::logger {

/**
 * @class logger::Logger
 *
 * @brief Logs a message to the available log sinks with a name.
 *
 * @details
 * - Provides public functions that return an empty log message to the user.
 * - The log message overloads operator<< to create log messages.
 * - When the log message is finished (deleted), the callback provided by this
 *   class will be called to start logging the message to the available log
 *   sinks.
 * - The available sinks could be determined from the file 'log_config.hpp'
 *   which is generated by CMake.
 *
 * @note
 * - All public functions are synchronous.
 * - All public functions are thread-safe.
 */
class Logger {
public:
  /**
   * @brief Constructor.
   *
   * @param name A name to identify the producer of the log message.
   */
  Logger(std::string name);

  /**
   * @brief Default destructor.
   */
  ~Logger() = default;

  /**
   * @brief Delete copy and move semantics.
   */
  Logger(const Logger &) = delete;
  Logger &operator=(const Logger &) = delete;
  Logger(Logger &&) = delete;
  Logger &operator=(Logger &&) = delete;

  LogMessageFactory debug();
  LogMessageFactory info();
  LogMessageFactory warn();
  LogMessageFactory error();

private:
  /**
   * @brief Name of the logger.
   */
  const std::string name_;

  /**
   * @brief Holds the events of this class to be handled later.
   */
  static std::shared_ptr<core::EventQueue> eventQueue_;

  /**
   * @brief Runs the events in 'queue_'.
   */
  static core::EventLoop eventLoop_;

  /**
   * @brief Signal bus that holds the signals for logging.
   */
  static std::shared_ptr<core::SignalBus> signalBus_;

  /**
   * @brief Unique pointer to the standard output sink.
   */
  static std::unique_ptr<StandardOutputSink> stdOutSink_;

  /**
   * @brief Unique pointer to the file sink.
   */
  static std::unique_ptr<FileSink> fileSink_;

  /**
   * @brief Indicates if the log sinks are created or not yet.
   */
  static std::once_flag isSinksInitialized_;

  /**
   * @brief Checks the configured log sinks and creates them.
   */
  static void initSinks();

  /**
   * @brief Creates and returns a 'LogMessage'.
   *
   * @return 'LogMessage'.
   */
  LogMessageFactory make(LogLevel lvl);
}; // class Logger

} // namespace helios::logger
